$('#index').click(function(){
			window.location.href='index.html';
		});
		$("#class").click(function(){
			window.location.href='class.html';
		});
		$("#cart").click(function(){
			window.location.href='cart.html';
		});
		$("#myXiu").click(function(){
			window.location.href='myXiu.html';
		});
		$("#more").click(function(){
			window.location.href='more.html';
		});